import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import ts from 'typescript'
const source = await readFile(new URL('../src/services/observationView.ts', import.meta.url), 'utf8')
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ES2022, target: ts.ScriptTarget.ES2022 } }).outputText
const v = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`)
const epoch = Date.parse('2026-10-09T00:00:00Z'), iso = n => new Date(epoch + n).toISOString()
const span = (id, type = 'tool', start = 0, end = 1000, parent = null, status = 'succeeded') => v.normalizeSpan({ span_id: id, task_id: 'fixture', parent_span_id: parent, name: `${type}.${id}`, operation_type: type, status, started_at: iso(start), finished_at: end === null ? null : iso(end), input_truncated: false, output_truncated: false })
const task = { status: 'succeeded', started_at: iso(0), created_at: iso(0), finished_at: iso(10000) }
// Parent/child overlap must not be added to the task wall time.
const overlap = [span('root', 'agent', 0, 10000), span('a', 'llm', 0, 7000, 'root'), span('b', 'llm', 3000, 10000, 'root')]
assert.equal(v.durationMs({ started_at: task.created_at, finished_at: task.finished_at }), 10000)
assert.equal(overlap.filter(v.isCall).reduce((sum, s) => sum + v.durationMs(s), 0), 14000)
assert.equal(v.timelineBounds(task, overlap, epoch + 99999).length, 10000)
assert.equal(v.timelineBounds({ ...task, status: 'running', finished_at: null }, overlap, epoch + 20000).length, 20000)
assert.equal(v.timelineBounds({ ...task, started_at: null }, overlap, epoch).origin, epoch)
assert.equal(v.durationMs(span('missing', 'tool', 0, null)), null)
assert.equal(v.durationMs(span('reversed', 'tool', 100, 0)), null)
assert.equal(v.durationMs({ started_at: 'invalid', finished_at: iso(1) }), null)
assert.equal(v.durationMs(span('zero', 'tool', 0, 0)), 0)
assert.equal(v.spanState(span('unknown', 'tool', 0, null, null, 'running'), false), '状态未确定')
assert.equal(v.spanState(span('live', 'tool', 0, null, null, 'running'), true), '执行中')
assert.equal(v.spanTime(span('interrupted', 'tool', 0, null, null, 'interrupted'), false, epoch + 500000), '耗时未知')
assert.equal(v.timelineBounds({ ...task, status: 'interrupted', finished_at: null }, [span('late', 'tool', 5000, null)], epoch + 500000).right, epoch + 5000)
// Historical malformed trees remain finite and retain every record once.
const malformed = [span('a', 'planning', 0, 1, 'b'), span('b', 'planning', 0, 1, 'a'), span('self', 'planning', 0, 1, 'self'), span('orphan', 'tool', 0, 1, 'missing')]
const forest = v.buildForest(malformed)
const allRows = v.traceRows(forest, new Set(forest.nodes.keys()), 'all', '', n => n)
assert.equal(allRows.length, 4)
assert.equal(new Set(allRows.map(r => r.node.span.span_id)).size, 4)
assert.ok(forest.nodes.get('orphan').warning.includes('缺失'))
assert.deepEqual(v.buildForest([...malformed].reverse()).roots, forest.roots)
assert.equal(v.ancestors(forest, 'self').length, 0)
const tree = v.buildForest([...overlap, span('error', 'tool', 0, 10, 'root', 'failed'), span('slow', 'tool', 0, 10000, 'root')])
assert.deepEqual(v.traceRows(tree, new Set(), 'model', '', n => n).map(r => r.node.span.span_id), ['root', 'a', 'b'])
assert.equal(v.traceRows(tree, new Set(), 'model', '', n => n)[0].context, true)
assert.deepEqual(v.traceRows(tree, new Set(), 'errors', '', n => n).map(r => r.node.span.span_id), ['root', 'error'])
assert.deepEqual(v.traceRows(tree, new Set(), 'slow', '', n => n).map(r => r.node.span.span_id), ['root', 'slow'])
assert.deepEqual(v.traceRows(tree, new Set(), 'all', '公交', n => n === 'tool.error' ? '查询公交路线' : n).map(r => r.node.span.span_id), ['root', 'error'])
assert.equal(v.traceRows(tree, new Set(), 'all', 'no such call', n => n).length, 0)
assert.equal(v.traceRows(tree, new Set(), 'all', '', n => n).length, 1)
assert.equal(v.defaultSelection(overlap), 'a')
assert.equal(v.defaultSelection([span('s', 'tool', 0, 20000), span('f', 'llm', 0, 1000)]), 'f')
assert.equal(v.defaultSelection([]), '')
assert.deepEqual(v.anomalyCounts([span('parent', 'agent', 0, 1, null, 'failed'), span('failed', 'tool', 0, 1, null, 'failed'), span('interrupted', 'llm', 0, null, null, 'interrupted'), span('unknown', 'tool', 0, null, null, 'running')]), { total: 2, failed: 1, interrupted: 1 })
const tokens = fields => v.normalizeSpan({ ...span('tokens', 'llm'), ...fields })
assert.equal(v.tokenTotal(tokens({ input_tokens: 0, output_tokens: 0 })), 0)
assert.equal(v.tokenTotal(tokens({ input_tokens: 2, output_tokens: 3, total_tokens: 9 })), 9)
assert.equal(v.tokenTotal(tokens({ input_tokens: 2, output_tokens: 3 })), 5)
assert.equal(v.tokenTotal(tokens({ input_tokens: 2 })), null)
assert.equal(v.tokenTotal(tokens({ total_tokens: 20 })), 20)
assert.equal(v.tokenTotal(tokens({})), null)
assert.equal(v.tokenText(0), '0')
assert.equal(v.tokenText(null), '未采集')
assert.equal(tokens({ input_tokens: NaN }).input_tokens, null)
const tools = [span('first', 'tool', 0, 10), span('second', 'tool', 0, 30), span('third', 'tool', 0, null, null, 'interrupted')].map(s => ({ ...s, name: 'tool.custom_future_tool' }))
const grouped = v.toolRows(tools)[0]
assert.equal(grouped.average, 20)
assert.equal(grouped.duration, 40)
assert.equal(grouped.total, 3)
assert.equal(grouped.timed, 2)
assert.equal(grouped.interrupted, 1)
assert.equal(grouped.successRate, 1)
assert.equal(v.toolRows([span('bad', 'tool', 1, 0)])[0].average, null)
assert.equal(v.isActive({ status: 'accepted' }), true)
assert.equal(v.isActive(task), false)
assert.equal(v.timingIssue(span('bad-order', 'tool', 10, 0)), '结束时间早于开始时间')
assert.equal(v.timingIssue({ started_at: 'invalid', finished_at: null }), '起止时间无效')
assert.equal(v.timingIssue(span('not-finished', 'tool', 0, null)), '')
assert.equal(v.anomalyCounts([span('validation', 'validation', 0, 10, null, 'failed'), span('returned', 'llm', 0, 7)]).total, 0)
const childOfCycle = v.buildForest([span('child', 'tool', 0, 1, 'cycle-a'), span('cycle-a', 'agent', 10, 20, 'cycle-b'), span('cycle-b', 'agent', 20, 30, 'cycle-a')])
assert.equal(childOfCycle.nodes.get('child').parent, 'cycle-a', 'break the cycle itself, preserve innocent child links')
assert.equal(v.traceRows(childOfCycle, new Set(childOfCycle.nodes.keys()), 'all', '', n => n).length, 3)
console.log('observationView: 53 boundary assertions passed')
