"""旅行规划 v4 强类型契约。"""

from .facts import (
    FactSource,
    FactStore,
    MapCoordinate,
    MissingField,
    PlaceFact,
    PlaceSearchData,
    ReferenceCost,
    RouteFact,
    RouteOption,
    RouteSegment,
    ToolError,
    ToolResult,
    TransitLine,
    TransitStop,
    WeatherFact,
    WeatherForecast,
)
from .input import (
    ArrivalBlockRule,
    DayConstraint,
    HardRequirement,
    PlanningInput,
    RequirementSummary,
    RuleSet,
    SlotConstraint,
    TripBudget,
    TripRequest,
)
from .plan import (
    AddActivity,
    AreaHint,
    DayRevision,
    DaySummary,
    DeleteActivity,
    DraftActivity,
    DraftDay,
    EditCommand,
    ItineraryPreview,
    LegEndpoint,
    LodgingProposal,
    LodgingRef,
    PlanDraft,
    PlanProposal,
    PreviewCalculation,
    ProposalActivity,
    ProposalDay,
    RepairState,
    ReorderActivities,
    RouteModeResult,
    RouteLeg,
    SelectLegMode,
    ValidationIssue,
    ValidationReport,
    RequirementResult,
    DayValidation,
)
from .tasks import CandidateRef, Subtask, TaskCoverage, TaskResult

__all__ = [
    "AddActivity", "AreaHint", "ArrivalBlockRule", "CandidateRef", "DayConstraint", "DayRevision", "DaySummary", "DayValidation", "DeleteActivity", "DraftActivity", "DraftDay", "EditCommand",
    "FactSource", "FactStore", "HardRequirement", "ItineraryPreview", "MapCoordinate",
    "LegEndpoint", "LodgingProposal", "LodgingRef", "MissingField", "PlaceFact", "PlaceSearchData", "PlanDraft", "PlanProposal", "ProposalActivity", "ProposalDay",
    "PlanningInput", "ReferenceCost", "RequirementSummary", "RouteFact", "RouteLeg",
    "RouteModeResult", "RouteOption", "RouteSegment", "RuleSet", "SelectLegMode", "SlotConstraint", "Subtask", "TaskCoverage", "TransitLine", "TransitStop",
    "PreviewCalculation", "RepairState", "ReorderActivities", "RequirementResult", "TaskResult", "ToolError", "ToolResult", "TripBudget", "TripRequest", "ValidationIssue",
    "ValidationReport", "WeatherFact", "WeatherForecast",
]
